# Generated by Django 5.0.6 on 2024-05-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nileblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
