# Generated by Django 5.0.6 on 2024-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nileblog', '0002_rename_comments_comment_rename_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='details_text',
            field=models.TextField(max_length=2000),
        ),
    ]
