# Generated by Django 5.0.6 on 2024-06-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nileblog', '0003_alter_article_details_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_text',
            field=models.CharField(max_length=200),
        ),
    ]
